channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=25.1
- pip:
  - mlflow==3.1.1
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==5.9.5
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==3.0.1
name: mlflow-env
